language: java
jdk:
  - oraclejdk7
  - oraclejdk8
services:
  - mongodb
addons:
  postgresql: "9.3"
env:
  matrix:
    - MODULE=!querydsl-scala
    - MODULE=querydsl-scala
install:
  - mvn -B -q install -DskipTests=true
before_script:
  - mysql -u root -e "source travis/mysql.sql"
  - psql -U postgres -f travis/postgresql.sql  
  - psql -c 'create extension postgis;' -d querydsl -U postgres
  - ./travis/cubrid.sh
  - ./travis/firebird.sh
script: mvn -B test -Pall,travis,examples --projects ${MODULE} jacoco:report
sudo: required

