language: java
jdk:
  - oraclejdk7
  - oraclejdk8
services:
  - mongodb
addons:
  postgresql: "9.3"
install:
  - sh -c 'cd querydsl-root && mvn -B -q install -DskipTests=true'
before_script:
  - mysql -u root -e "source travis/mysql.sql"
  - psql -U postgres -f travis/postgresql.sql  
  - psql -c 'create extension postgis;' -d querydsl -U postgres
  - ./travis/cubrid.sh
  - ./travis/firebird.sh
script:
  - jdk_switcher use openjdk6
  - sh -c 'cd querydsl-root && mvn -B test -Pall,travis'

